[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
remappings = [
  "openzeppelin-contracts/=contracts/lib/openzeppelin-contracts/"
]