[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
ignored_paths = [
  "lib/**/certora/**",
  "lib/**/test/**",
  "lib/**/docs/**",
  "src/YansToken.sol",
]

[[profile.default.fs_permissions]]
access = "read"
path = "out"

[[profile.default.fs_permissions]]
access = "read"
path = "out-validate"

[[profile.default.fs_permissions]]
access = "read"
path = "src"

[profile.validate]
inherits = "default"
ignored_paths = [
  "lib/**/certora/**",
  "lib/**/test/**",
  "lib/**/docs/**",
  "src/YansToken.sol",
  "test/**"
]
